[package]
name = "octopus-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
anydoc = { workspace = true }
htmd = { workspace = true }
walkdir = { workspace = true }
regex = "1"
url = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "gzip", "blocking"] }
encoding_rs = "0.8"
