//! Shell 内置命令补全表（约 50 条常用命令）。

pub struct CmdDef {
    pub name: &'static str,
    pub desc: &'static str,
}

pub static BUILTIN_COMMANDS: &[CmdDef] = &[
    CmdDef { name: "ls", desc: "列出目录" },
    CmdDef { name: "ll", desc: "详细列表" },
    CmdDef { name: "la", desc: "列出全部(含隐藏)" },
    CmdDef { name: "cd", desc: "切换目录" },
    CmdDef { name: "pwd", desc: "当前路径" },
    CmdDef { name: "cp", desc: "复制" },
    CmdDef { name: "mv", desc: "移动/重命名" },
    CmdDef { name: "rm", desc: "删除" },
    CmdDef { name: "mkdir", desc: "建目录" },
    CmdDef { name: "touch", desc: "建空文件" },
    CmdDef { name: "cat", desc: "查看文件" },
    CmdDef { name: "grep", desc: "文本搜索" },
    CmdDef { name: "find", desc: "查找文件" },
    CmdDef { name: "chmod", desc: "改权限" },
    CmdDef { name: "chown", desc: "改属主" },
    CmdDef { name: "tar", desc: "归档" },
    CmdDef { name: "zip", desc: "压缩 zip" },
    CmdDef { name: "unzip", desc: "解压 zip" },
    CmdDef { name: "echo", desc: "输出" },
    CmdDef { name: "head", desc: "文件头部" },
    CmdDef { name: "tail", desc: "文件尾部" },
    CmdDef { name: "wc", desc: "统计行/词/字节" },
    CmdDef { name: "sort", desc: "排序" },
    CmdDef { name: "uniq", desc: "去重" },
    CmdDef { name: "diff", desc: "比较差异" },
    CmdDef { name: "ssh", desc: "远程登录" },
    CmdDef { name: "scp", desc: "远程复制" },
    CmdDef { name: "ping", desc: "网络连通" },
    CmdDef { name: "curl", desc: "HTTP 请求" },
    CmdDef { name: "wget", desc: "下载" },
    CmdDef { name: "ifconfig", desc: "网络接口" },
    CmdDef { name: "netstat", desc: "网络状态" },
    CmdDef { name: "ps", desc: "进程列表" },
    CmdDef { name: "kill", desc: "结束进程" },
    CmdDef { name: "top", desc: "进程监控" },
    CmdDef { name: "df", desc: "磁盘用量" },
    CmdDef { name: "du", desc: "目录用量" },
    CmdDef { name: "git", desc: "版本控制" },
    CmdDef { name: "git status", desc: "查看状态" },
    CmdDef { name: "git diff", desc: "查看差异" },
    CmdDef { name: "git log", desc: "提交历史" },
    CmdDef { name: "git add", desc: "暂存" },
    CmdDef { name: "git commit", desc: "提交" },
    CmdDef { name: "git push", desc: "推送" },
    CmdDef { name: "git pull", desc: "拉取" },
    CmdDef { name: "docker", desc: "容器" },
    CmdDef { name: "docker ps", desc: "容器列表" },
    CmdDef { name: "cargo", desc: "Rust 包管理" },
    CmdDef { name: "cargo build", desc: "构建 Rust" },
    CmdDef { name: "cargo test", desc: "测试 Rust" },
    CmdDef { name: "npm", desc: "Node 包管理" },
    CmdDef { name: "node", desc: "Node 运行时" },
    CmdDef { name: "python3", desc: "Python 3" },
    CmdDef { name: "pip3", desc: "Python 包" },
    CmdDef { name: "brew", desc: "Homebrew" },
    CmdDef { name: "open", desc: "打开文件/应用" },
];
