[package]
name = "octopus-ocr"
version = "0.1.0"
edition = "2021"
include = ["src/**/*", "assets/words_alpha.txt"]

[dependencies]
octopus-infra = { path = "../infra" }
octopus-paddle-ocr = { path = "../paddle-ocr" }
parking_lot = { workspace = true }
image = "0.25"
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
