[package]
name = "octopus-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
once_cell.workspace = true
octopus-infra = { path = "../infra" }
regex = "1"

[dev-dependencies]
octopus-asr-local = { path = "../asr-local" }
