[package]
name = "octopus-download"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["stream", "http2", "rustls-tls", "json"] }
tokio.workspace = true
tokio-util = { version = "0.7", features = ["rt"] }
futures = "0.3"
sha2.workspace = true
thiserror = "2"
serde.workspace = true
serde_json.workspace = true
log.workspace = true

[dev-dependencies]
httpmock = "0.8"
tokio = { workspace = true, features = ["test-util"] }
tempfile = "3"
